#!/bin/bash

# Check if there are enough arguments
if [ $# -lt 2 ]; then
    echo "Error: You must provide exactly two arguments."
    echo "Usage: <project_name> <binary_name>"
    exit 1
fi

# Retrieve the folder name to be created from the first parameter
project_name=$1
binary_name=$2

# Check if the folder already exists
if [ -d "$project_name" ]; then
    echo "Error: The folder $project_name already exists. Choose another name."
    exit 1
fi

# Create the new folder
mkdir "$project_name"

# Reference folder containing the folders to copy
reference_folder="$HOME/my_scripts/Template"

# Check if the reference folder exists
if [ ! -d "$reference_folder" ]; then
    echo "Error: The reference folder does not exist. Please specify a valid path."
    exit 1
fi

# Copy folders from the reference folder to the new folder
cp -r "$reference_folder"/* "$project_name"
cp "$reference_folder/.gitignore" "$project_name/"
cp -r "$reference_folder/.github" "$project_name/"

cd "$project_name" || exit

sed -i "s|\bproject_name\b|$project_name|" "Makefile"
sed -i "s|\bbinary_name\b|$binary_name|" "Makefile"
sed -i "s|\bbinary_name\b|$binary_name|" ".gitignore"

cd "src" || exit

sed -i "s|\bproject_name\b|$project_name|" "main.c"

cd ".." || exit

cd ".github/workflows" || exit

sed -i "s|\bproject_name\b|$project_name|" "action.yml"
sed -i "s|\bbinary_name\b|$binary_name|" "action.yml"

echo "The folder $project_name has been successfully created, and the folders have been copied."
echo "The binary name $binary_name in the Makefile has been applied"

exit 0
